### PR TITLE
Don't inject js/css from purposes created by non-owners

### PR DESCRIPTION
**Pull request by bhuga**
cc @mastahyeti. This adds a check that refuses to inject css/js unless a team owner was the last person to edit the channel purpose that references them. An improvement if not perfect.

### CODE REVIEW

**Comment by bhuga** [comment]
Easier to read without whitespace at https://github.com/bhuga/hackable-slack-client/pull/4/files?w=1

**Comment by btoews** [comment]
That sounds like a reasonable approach.

**Comment by bhuga** [comment]
cc @jwietelmann @dvillega I haven't shipped this yet, but going forward only team owners will be allowed to update a purpose to inject js. I'll give you a week or so.

**Comment by dvillega** [comment]
I think it's fantastic.  We will be getting other people on the team involved around a PR / chat deploy option for updating that js file.  No need to have everyone touch the purpose.

**Pull request merged**
